@baseUrl = http://localhost:3000
@renderUrl = https://cse341-node-au0q.onrender.com

### Health check
GET {{baseUrl}}/

### Get all contacts (local)
GET {{baseUrl}}/contacts

### Get one contact by id (local)
GET {{baseUrl}}/contacts/000000000000000000000000

### Get all contacts (Render/production)
GET {{renderUrl}}/contacts

### Get one contact by id (Render/production)
GET {{renderUrl}}/contacts/000000000000000000000000